apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: log-service:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: log-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
